import static org.junit.Assert.*;

import org.junit.*;

public class LaboonCoinTest {

    // Assert that creating a new LaboonCoin instance
    // does not return a null reference
    @Test
    public void testLaboonCoinExists() {
	LaboonCoin l = new LaboonCoin();
	assertNull(l);
    }

    // Assert that a hash can be generated by the hash function
    @Test
    public void testBasicHash() {
	String str = "loop00002815";
    LaboonCoin l = new LaboonCoin();

    int hash = 0;
    hash = l.hash(str);
	assertEquals(hash, Integer.parseInt("00086d30", 16));
    }

    // Assert that a hash can be generated by the hash function
    @Test
    public void testLongHash() {
	String str = "boo";
    LaboonCoin l = new LaboonCoin();

    int hash = 0;
    hash = l.hash(str);
	assertEquals(hash, Integer.parseInt("551fda32", 16));
    }

    // Assert that a hash is not generated when a null string is entered
    @Test
    public void testNullHash() {
    LaboonCoin l = new LaboonCoin();

    try {
            int hash = l.hash(null);
    } catch (IllegalArgumentException e) {
       return; 
    }
    fail("No IllegalArgumentException thrown");
    }    

    // Assert that a hash can be generated by the hash function
    @Test
    public void testInvalidHash() {
	int hash = Integer.valueOf("002343as", 16);
    LaboonCoin l = new LaboonCoin();

    int hash = 0;
    hash = l.hash(str);
	assertNotEquals(hash, 0);
    }
}
